project:
  type: website
  output-dir: _site

  
website:
  title: "My Learning Things"
  bread-crumbs: false
  page-navigation: true
  navbar:
    logo: src/assets/img/logo.png
    logo-href: src/index.qmd
    background: dark
    pinned: true
    title: false
    left:
      - icon: house-heart-fill
        text: "Home"
        href: index.qmd
      - icon: clipboard-heart-fill
        text: "My Notes"
        href: src/my-notes.qmd
        
  sidebar: 
    - id: notes-sass
      style: docked
      collapse-level: 2
      align: left
      background: light
      pinned: true
      logo: src/assets/img/sass.png
      logo-href: src/pages/sass/index.qmd
      contents: 
        - section: Resumos
          href: src/pages/sass/index.qmd
          contents:
            - section: Introdução
              contents: 
                - src/pages/sass/a1-sass.qmd
                - src/pages/sass/a2-sass.qmd
            - section: Regras de Estilo
              contents: 
                - src/pages/sass/b1-sass.qmd
                - src/pages/sass/b2-sass.qmd
                - src/pages/sass/b3-sass.qmd
            




format:
  html:
    highlight-style: dracula
    fontsize: 18px
    theme:
      - pulse
      - brand
    css: assets/styles.css
    toc: true
    toc-expand: true
    grid: 
      content-mode: auto
      sidebar-width: 20%
      margin-width: 20%
      gutter-width: 3em

      
editor: visual


freeze: auto

