project:
  type: website
  output-dir: docs

website:
  title: "My Learning Things"
  bread-crumbs: false
  favicon: src/assets/logo.png
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    pinned: true
    title: false
    left:
      - icon: house-heart-fill
        href: index.qmd
        text: Home
      - icon: clipboard-heart-fill
        href: src/my-notes.qmd
        text: "My Notes"
        
  sidebar: 
    - id: sass
      style: docked
      background: light
      pinned: true
      alignment: center
      logo: src/assets/img/sass.png
      logo-href: /src/pages/sass/index.qmd
      contents: 
        - section: Introdução
          href: src/pages/sass/index.qmd
          contents: 
            - src/pages/sass/a1-sass.qmd
            - src/pages/sass/a2-sass.qmd
        - section: Regras de Estilo
          contents: 
           - src/pages/sass/b1-sass.qmd
            

format:
  html:
    highlight-style: dracula
    fontsize: 18px
    theme:
      - pulse
      - brand
    css: src/assets/styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 3rem
      
      
editor: visual

