---
title: "Sintaxe"
format: html
toc: true
---

O Sass oferece duas sintaxes distintas. Ambas são compatíveis entre si, o que
permite que você e sua equipe escolham a que melhor se adapta ao fluxo de
trabalho adotado.

## SCSS

A sintaxe SCSS utiliza a extensão de arquivo `.scss`. Com poucas exceções, ela é
um superconjunto do CSS, o que significa que todo código CSS válido também é
considerado válido em SCSS. Por ser mais próxima da sintaxe tradicional do CSS,
esta é a forma mais comum e acessível de se utilizar o Sass.

Abaixo, um exemplo de SCSS:

``` scss

@mixin button-base() {
  @include typography(button);
  @include ripple-surface;
  @include ripple-radius-bounded;

  display: inline-flex;
  position: relative;
  height: $button-height;
  border: none;
  vertical-align: middle;

  &:hover {
    cursor: pointer;
  }

  &:disabled {
    color: $mdc-button-disabled-ink-color;
    cursor: default;
    pointer-events: none;
  }
}
```

### Sintaxe Recuada (Sass)

A sintaxe recuada, que originalmente nomeava a linguagem Sass, utiliza a
extensão `.sass`. Diferente do SCSS, ela não emprega chaves ou ponto e vírgula,
adotando o recuo (indentação) como estrutura sintática.

Apesar de suportar os mesmos recursos do SCSS, a sintaxe recuada apresenta
restrições, como a impossibilidade de expressões quebradas em múltiplas linhas.

Exemplo em sintaxe recuada:

``` scss
@mixin button-base()
  @include typography(button)
  @include ripple-surface
  @include ripple-radius-bounded

  display: inline-flex
  position: relative
  height: $button-height
  border: none
  vertical-align: middle

  &:hover
    cursor: pointer

  &:disabled
    color: $mdc-button-disabled-ink-color
    cursor: default
    pointer-events: none
```

--------------------------------------------------------------------------------

::: callout-warning
## Atenção: a sintaxe recuada não suporta expressões quebradas em várias linhas, conforme identificado no problema [#216](https://github.com/sass/sass/issues/216).
:::
